# Generated by Django 5.1.6 on 2025-04-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhatnt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
