# Generated by Django 5.1.6 on 2025-04-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhatnt', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhatnt.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='RoundTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupLocation', models.CharField()),
                ('dropLocation', models.CharField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickupDate', models.DateField()),
                ('pickupTime', models.TimeField()),
                ('returnDate', models.DateField()),
                ('tripType', models.CharField(choices=[('oneway', 'oneway'), ('roundtrip', 'roundtrip'), ('rental', 'rental')], default='', max_length=20)),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhatnt.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupLocation', models.CharField()),
                ('pickupDate', models.DateField()),
                ('pickupTime', models.TimeField()),
                ('rentalDuration', models.IntegerField()),
                ('tripType', models.CharField(choices=[('oneway', 'oneway'), ('roundtrip', 'roundtrip'), ('rental', 'rental')], default='', max_length=20)),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhatnt.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='OneWayTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupLocation', models.CharField()),
                ('dropLocation', models.CharField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickupDate', models.DateField()),
                ('pickupTime', models.TimeField()),
                ('tripType', models.CharField(choices=[('oneway', 'oneway'), ('roundtrip', 'roundtrip'), ('rental', 'rental')], default='', max_length=20)),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhatnt.vehicletype')),
            ],
        ),
    ]
