# Generated by Django 5.1.6 on 2025-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhatnt', '0004_vehicletype_vehicle_roundtrip_rental_onewaytrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='onewaytrip',
            name='totalFare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
