# Generated by Django 5.1.6 on 2025-04-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhatnt', '0005_onewaytrip_totalfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtrip',
            name='totalFare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
