# Generated by Django 5.1.6 on 2025-05-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhatnt', '0006_roundtrip_totalfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='onewaytrip',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhatnt.userdata'),
        ),
        migrations.AddField(
            model_name='rental',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhatnt.userdata'),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhatnt.userdata'),
        ),
    ]
